version: '3'

networks:
  ovh1-network:
    external: true
    name: ovh1-network

services:
  litteratur_api:
    image: radoor/litteratur-api:0.1.22
    container_name: litteratur-api
    volumes:
      - ./data/litteratur-static:/litteratur/static/frontpageimages
    ports:
      - 3389:8080
    env_file:
      - .env.prod

    networks:
      - ovh1-network

    command: "gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 app:app"


  litteratur-frontend:
    image: radoor/litteratur:0.1.15
    ports:
      - "8134:80"

    command: "nginx -g 'daemon off';"

    networks:
      - ovh1-network
